### ISSUE TITLE
Practice area template

### ISSUE THREAD

**Issue by tripledoublev** [hyphacoop/hypha.coop#340]
I started a layout template called [practice area](https://github.com/hyphacoop/hypha.coop/blob/master/_layouts/practice_area.html). 

It allows each practice area to build their own page with this specific template.
This page is meant to showcase the practice's service offering.

Summary of structure

- Practice area title 
- Description of practice area
- Services
- Selected projects

Here is the current front matter template implemented:

```
title: string
excerpt: string
image: string
diagram: string
diagram_alt_text: string
description:  string 
tagline: string
services: list of service objects

# Service Object
service:
  - title: string
    description: string or list of string (items become paragraph)
    list: optional list of string 
```

I created [this html file](https://github.com/hyphacoop/hypha.coop/blob/pa-template/pa-template.html) that is ready to be filled by other practice areas.

You can look at the [co-creation lab](https://github.com/hyphacoop/hypha.coop/blob/master/co-creation-lab.html) or the [data provenance](https://github.com/hyphacoop/hypha.coop/blob/master/data-provenance.html) page to see how the template can be used.

The template will show projects associated with the practice area when the project's `preview` key is set to `true`

The newly created practice area page will be accessible from both the work and the home page.

I am looking for feedback on the content structure in order to implement a template that will serve all practice areas.
